baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "Momom"
theme = "hugo-developer-portfolio"

[module]
  [[module.imports]]
      path = "github.com/samrobbins85/hugo-developer-portfolio"
[params.plugins]
# CSS Plugins
[[params.plugins.css]]
URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"
# JS Plugins
[[params.plugins.js]]
URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
[[params.plugins.js]]
URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"

[menu]
[[menu.main]]
name = "About"
URL = "about"
[[menu.main]]
name = "Blog"
URL = "blog"
[[menu.main]]
name = "Contact"
URL = "contact"

[params]
home = "Home" # What you want the homepage to show up as in the menu bar
# Meta data
description = "The website of momom, 2nd Year Computer Science Master's course Student"
author = "momom"

  [params.contact]
  formAction = "https://formspree.io/f/mwkaklgb"

  [params.footer]
  email = "shakefureeeku@gmail.com"
  address = "Tokyo, JP"
